// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	partner_transfers_defs "gitlab.fbs-d.com/backend/legacy/common/partner-transfers/definitions"
	excp "gitlab.fbs-d.com/dev/go/legacy/exceptions"
	api "gitlab.fbs-d.com/dev/go/legacy/helpers/api"
	rmq "gitlab.fbs-d.com/dev/go/legacy/rmq/v2"
	reflect "reflect"
)

// MockIInternalTransfersClient is a mock of IInternalTransfersClient interface
type MockIInternalTransfersClient struct {
	ctrl     *gomock.Controller
	recorder *MockIInternalTransfersClientMockRecorder
}

// MockIInternalTransfersClientMockRecorder is the mock recorder for MockIInternalTransfersClient
type MockIInternalTransfersClientMockRecorder struct {
	mock *MockIInternalTransfersClient
}

// NewMockIInternalTransfersClient creates a new mock instance
func NewMockIInternalTransfersClient(ctrl *gomock.Controller) *MockIInternalTransfersClient {
	mock := &MockIInternalTransfersClient{ctrl: ctrl}
	mock.recorder = &MockIInternalTransfersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIInternalTransfersClient) EXPECT() *MockIInternalTransfersClientMockRecorder {
	return m.recorder
}

// Init mocks base method
func (m *MockIInternalTransfersClient) Init(r rmq.IRmq) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Init", r)
}

// Init indicates an expected call of Init
func (mr *MockIInternalTransfersClientMockRecorder) Init(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockIInternalTransfersClient)(nil).Init), r)
}

// StartTwoPhasedInternalTransferV1 mocks base method
func (m *MockIInternalTransfersClient) StartTwoPhasedInternalTransferV1(token string, client api.Client, transferKey string, fromAccountId, toAccountId, amount int64) (*partner_transfers_defs.StartTwoPhasedInternalTransferResponseV1, excp.IException) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTwoPhasedInternalTransferV1", token, client, transferKey, fromAccountId, toAccountId, amount)
	ret0, _ := ret[0].(*partner_transfers_defs.StartTwoPhasedInternalTransferResponseV1)
	ret1, _ := ret[1].(excp.IException)
	return ret0, ret1
}

// StartTwoPhasedInternalTransferV1 indicates an expected call of StartTwoPhasedInternalTransferV1
func (mr *MockIInternalTransfersClientMockRecorder) StartTwoPhasedInternalTransferV1(token, client, transferKey, fromAccountId, toAccountId, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTwoPhasedInternalTransferV1", reflect.TypeOf((*MockIInternalTransfersClient)(nil).StartTwoPhasedInternalTransferV1), token, client, transferKey, fromAccountId, toAccountId, amount)
}

// CompleteTwoPhasedInternalTransferV1 mocks base method
func (m *MockIInternalTransfersClient) CompleteTwoPhasedInternalTransferV1(token string, client api.Client, transferId int64) (*partner_transfers_defs.CompleteTwoPhasedInternalTransferResponseV1, excp.IException) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTwoPhasedInternalTransferV1", token, client, transferId)
	ret0, _ := ret[0].(*partner_transfers_defs.CompleteTwoPhasedInternalTransferResponseV1)
	ret1, _ := ret[1].(excp.IException)
	return ret0, ret1
}

// CompleteTwoPhasedInternalTransferV1 indicates an expected call of CompleteTwoPhasedInternalTransferV1
func (mr *MockIInternalTransfersClientMockRecorder) CompleteTwoPhasedInternalTransferV1(token, client, transferId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTwoPhasedInternalTransferV1", reflect.TypeOf((*MockIInternalTransfersClient)(nil).CompleteTwoPhasedInternalTransferV1), token, client, transferId)
}
